/*
 * Copyright (C) 2026 Neil Rackett
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Auto-generated -- do not edit by hand.
 * Source: keymaps.txt
 */
#pragma once

static const char zx_builtin_keymaps[] =
    "#START do not remove this comment\n"
    "#\n"
    "# See README for this file format. Note that to\n"
    "# map buttons to space, the ~ character must be used.\n"
    "#\n"
    "# IMPORTANT: extended keymaps (starting with \"x\") must\n"
    "# be the FIRST entries in a map.\n"
    "\n"
    "# Scuba Dive\n"
    "MATCH:* SCUBA DIVE *\n"
    "xul2    up+left = 2, select level 2\n"
    "xur3    up+right = 3, select level 3\n"
    "xuf4    up+fire = 4, select level 4\n"
    "lx      left = x\n"
    "rz      right = z\n"
    "fm      fire = m\n"
    "dn      down = n\n"
    "u1      up = 1, select level 1\n"
    "@10:k1  Frame 10, press k to redefine keys\n"
    "@14:z1  Redefine left\n"
    "@16:x1  Redefine right\n"
    "@18:m1  Redefine accelerate\n"
    "@20:n1  Redefine decelerate\n"
    "\n"
    "# Bombjack\n"
    "MATCH:Elite Systems Presents\n"
    "AND-MATCH:BEST BOMBERS\n"
    "l1|l    left = 1 and Kempstone left\n"
    "r2|r    right = 2 and Kempstone right\n"
    "fp|u    fire = p and Kempstone up\n"
    "dp|d    down = p and Kempstone down\n"
    "u5|f    up = 5 and Kempstone fire\n"
    "\n"
    "# Jetpack.\n"
    "MATCH:JETPAC IS LOADING\n"
    "l1|l\n"
    "r2|r\n"
    "f4|f\n"
    "d|f|u   Up + fire combo for simpler playing\n"
    "u5|u\n"
    "@10:41  Press 4 at frame 10 to select Kempstone\n"
    "\n"
    "# Thrust. Give it a bit more redrawing time with scanline period of 170.\n"
    "MATCH:>>>THRUST<<<\n"
    "SCANLINE-PERIOD:170\n"
    "la|l\n"
    "rs|r\n"
    "fim\n"
    "dm|d\n"
    "up|u\n"
    "@20:n1      Do you want to refine keys? [N]o\n"
    "\n"
    "# Loderunner.\n"
    "MATCH:BRODERBUND SOFTWARE(SLODE RUNNER\n"
    "l1|l\n"
    "r2|r\n"
    "f0|f\n"
    "d3|d\n"
    "u5|u\n"
    "@20:01      Leave splash screen\n"
    "@70:21      Select joystick\n"
    "\n"
    "# IK+\n"
    "MATCH:DEFLECT@BALLS@FOR\n"
    "AND-MATCH:A@LOST@NINJA<<<<\n"
    "l1|l\n"
    "r2|r\n"
    "f5|f\n"
    "d3|d\n"
    "u4|u\n"
    "@20:01      Leave splash screen\n"
    "@30:01      Leave credits screen\n"
    "@40:51      Player 1 select joystick\n"
    "@50:n1      No player 2\n"
    "\n"
    "# BMX simulator\n"
    "# Give it a bit more redrawing time with scanline period of 170.\n"
    "MATCH:BMX\n"
    "AND-MATCH:6COURSE|RACE|PRESS 9A 9FOR 6ACTION\n"
    "SCANLINE-PERIOD:170\n"
    "l6      6 = left\n"
    "r7      7 = right\n"
    "f0      0 = accelerate\n"
    "d~      Space = exit demo\n"
    "us      S = start game\n"
    "\n"
    "# Skooldaze. Here there are too many keys, so we resort\n"
    "# to extended mapping.\n"
    "# Also set a scanline period if 85 to make the game faster.\n"
    "MATCH:YOU HAVE OVER 10000 LINES TO WRITE\n"
    "SCANLINE-PERIOD:85\n"
    "xdlf        Down+left = fire capatult\n"
    "xuls        Up+left = sit down/up\n"
    "xurl        Up+right = leap\n"
    "xufj        Up+fire = jump\n"
    "xudn        Up+n = [N]o to using your names.\n"
    "xlfu        Left+fire = [U]understand.\n"
    "lo|l\n"
    "rp|r\n"
    "fh|f        Hit\n"
    "da|d\n"
    "uq|u\n"
    "\n"
    "# Sabre Wulf\n"
    "MATCH:SABRE WULF IS LOADING\n"
    "l|l\n"
    "r|r\n"
    "f4|f    4 = Select kempstone\n"
    "d0|d    0 = Start game\n"
    "u|u\n"
    "\n"
    "# Sanxion\n"
    "MATCH:SANXION . . . THE SPECTRUM REMIX\n"
    "l|l\n"
    "r|r\n"
    "f1|r    1 = Start game\n"
    "d|d\n"
    "u|u\n"
    "@40:33  3 = Select Kempstone (take down for 3 frames)\n"
    "\n"
    "# Pac-Man by Marco Leal\n"
    "MATCH:PAC-MAN\n"
    "AND-MATCH:MARCO LEAL\n"
    "lo\n"
    "rp\n"
    "fs      S = Start game\n"
    "da\n"
    "uq\n"
    "\n"
    "# Default keymap used for all the games that don't match\n"
    "DEFAULT:\n"
    "xuly\n"
    "xurn\n"
    "xuf~ # ~ is mapped to space\n"
    "l1|l\n"
    "r2|r\n"
    "u3|u\n"
    "d4|d\n"
    "f5|f\n"
    "\n"
    "#END do not remove this comment\n"
;
